### ISSUE TITLE
Unable to run ./configure

### ISSUE THREAD

**Issue by heliomass** [rrthomas/plptools#2]
Hi,

I'm probably missing something obvious, but there's no `configure` file in the repository, so the following command fails:

```shell
$ ./configure
zsh: no such file or directory: ./configure
```

If this isn't an issue, can you let me know where I'm going wrong?

Note I'm attempting to compile this on a Mac (OS X v10.11.2):

```shell
$ uname -mprv
15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64 i386
```

Thanks.

**Comment by rrthomas** [comment]
You're missing something: see the "Information for developers" section at the bottom of `README`. I've tried to clarify the instructions to make this less likely for other users; thanks for reporting this problem.

**Comment by heliomass** [comment]
Thanks! I shall have a try this evening. It's great to see that this project is still being looked after :)
