### ISSUE TITLE
Add pointer to documentation from README

### ISSUE THREAD

**Issue by mikeydelamonde** [rrthomas/plptools#8]
Hi there,

Firstly, thanks for writing this - I have frankensteined a Psion 5mx together and want to try to use it! 

I have got the build to work - only change was I had to install GNU install so that I could use the -D flag, so changed the Makefile.am to say ginstall -D.

Now it's installed, what do I do now? Do I need to get "ncpd" to run as a daemon? I wondered if there was any docs on the next steps?

Thanks, Mike

**Comment by rrthomas** [comment]
Thanks for answering, @kapfab. @mikeydelamonde, if there's something missing or wrong in the docs, please file an issue. I can see in particular that there's no pointer from the `README` to the docs, so I'll add that.

**Comment by kapfab** [comment]
Beware, macOS natively supports many (if not most) USB-to-Serial adapters (Silicon Labs, Prolific, FTDI, WCH) but some built-in drivers don’t handle all signals, even though the cable is properly wired…

**Comment by kapfab** [comment]
Regarding `install -D`, I don’t know which option is the best for macOS: both `install -d` (which works in this case as the target is a directory) and `ginstall -D` will imply a macOS-specific change.

**Comment by rrthomas** [comment]
`install -D` is indeed non-portable, I'll fix that too.

**Comment by kapfab** [comment]
We could use `uname` to tweak the install command for Linux and macOS, but I don’t know the compatibility status of `uname` and `install` on all the other supported OS.

**Comment by rrthomas** [comment]
I'll make a new release shortly with the fixes included.

**Comment by rrthomas** [comment]
1.0.17 now released.

**Comment by kapfab** [comment]
CTS and DSR should be 1.
Just to make sure, is the remote link enabled on your Psion?

**Comment by mikeydelamonde** [comment]
Hi all, Quick update in case you were interested - I bought a new cable, and it now works!
